name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Create environment file
        run: |
          cd frontend
          echo "REACT_APP_CESIUM_API_KEY=${{ secrets.CESIUM_API_KEY }}" > .env

      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          CI: false

      - name: Replace Cesium API Key
        run: |
          find ./frontend/build -name "*.html" -type f -exec sed -i 's/CESIUM_API_KEY_PLACEHOLDER/${{ secrets.CESIUM_API_KEY }}/g' {} \;
        env:
          CESIUM_API_KEY: ${{ secrets.CESIUM_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
